# Generated by Django 4.2.4 on 2023-08-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('des', models.CharField(max_length=250, verbose_name='Designation')),
                ('instagram', models.CharField(max_length=2250, verbose_name='Instagram')),
                ('github', models.CharField(max_length=2250, verbose_name='github')),
                ('linkedin', models.CharField(max_length=2250, verbose_name='linkedin')),
                ('website', models.CharField(max_length=2250, verbose_name='website')),
                ('twitter', models.CharField(max_length=2250, verbose_name='twitter')),
            ],
        ),
    ]
