# Generated by Django 4.2.4 on 2023-08-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(default=1, upload_to='team', verbose_name='Profile'),
            preserve_default=False,
        ),
    ]
