# Generated by Django 4.2.4 on 2023-08-22 05:49

from django.db import migrations, models
import homepages.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0003_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(upload_to=homepages.models.custom_upload_team, verbose_name='Profile'),
        ),
    ]
