# Generated by Django 4.2.4 on 2023-08-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0004_alter_team_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Front_page_ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='banner/frontpage', verbose_name='Image 1920*650')),
            ],
        ),
    ]
