# Generated by Django 4.2.4 on 2023-08-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=250, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('certificate_for', models.CharField(max_length=250, verbose_name='Certificate For')),
                ('image', models.ImageField(upload_to='certificate/verify', verbose_name='Certificate image')),
            ],
        ),
    ]
