# Generated by Django 4.2.4 on 2023-08-21 19:37

import certificate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0003_certificate_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(upload_to=certificate.models.custom_upload_to, verbose_name='Certificate image'),
        ),
    ]
