# Generated by Django 4.2.4 on 2023-08-22 05:40

import certificate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0005_remove_certificate_certificate_for_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='offerletter_for',
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_for',
            field=models.CharField(default=1, max_length=250, verbose_name='Certificate For'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(upload_to=certificate.models.custom_upload_to, verbose_name='Certificate image'),
        ),
    ]
