# Generated by Django 4.2.4 on 2023-08-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_blog_blogdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetails',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
