# Generated by Django 4.2.4 on 2023-08-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_nexelyoutubelearn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('linkedin', models.URLField(max_length=2220, verbose_name='LinkedIN ')),
                ('college', models.CharField(max_length=250, verbose_name='College Name')),
                ('haq', models.CharField(max_length=250, verbose_name='Highest Qualification')),
                ('current_year', models.CharField(max_length=50, verbose_name='Current Year')),
                ('internship', models.CharField(max_length=50, verbose_name='Internship')),
                ('cover_letter', models.TextField(verbose_name='Cover Letter')),
            ],
        ),
    ]
