# Generated by Django 4.2.4 on 2023-08-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0004_career_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='career_form',
            name='exp',
            field=models.CharField(default=1, max_length=50, verbose_name='Required Experience'),
            preserve_default=False,
        ),
    ]
