# Generated by Django 4.2.4 on 2023-08-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0005_career_form_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='career_form',
            name='des',
            field=models.TextField(default=1, verbose_name='Short Description'),
            preserve_default=False,
        ),
    ]
