# Generated by Django 4.2.4 on 2023-08-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0006_career_form_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='career_form',
            name='img',
            field=models.ImageField(default=1, upload_to='career/career', verbose_name='Banner Image 690*520'),
            preserve_default=False,
        ),
    ]
