# Generated by Django 4.2.4 on 2023-08-28 15:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0007_career_form_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='career_form',
            name='req1',
            field=models.CharField(default=1, max_length=250, verbose_name='Requirements 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career_form',
            name='req2',
            field=models.CharField(default=1, max_length=250, verbose_name='Requirements 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career_form',
            name='req3',
            field=models.CharField(default=1, max_length=250, verbose_name='Requirements 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career_form',
            name='responsibilities',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Responsibilities'),
            preserve_default=False,
        ),
    ]
